### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by omerihtizaz** [alizahidraja/hand-paint#1]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://alizahidraja-hand-paint-streamlit-app-jrw5eu.streamlit.app/alizahidraja/hand-paint/main) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by alizahidraja** [comment]
Hey!
Thanks for the update
I have restarted the app, let me know if it goes over its limit again!
